#light
open System
open AshleyIngram.Euler.Common.MathExtensions

/// <summary>
/// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
/// By starting with 1 and 2, the first 10 terms will be:
/// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
///
/// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
/// find the sum of the even-valued terms.
/// </summary>

[<EntryPoint>]
let main argv = 
    let seq = Math.FibonacciSequence |> Seq.takeWhile(fun i -> i < 4000000) |> Seq.toList

    let result = seq |> List.filter(fun n -> n % 2 = 0) |> List.sum
    printfn "Result = %A" result
    Console.ReadLine() |> ignore
    0 // return an integer exit code